services:
  db:
    image: postgres:16
    container_name: tareas_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: gestor-tareas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
    - db_data:/var/lib/postgresql/data

    networks:
    - app_net

  backend:
    build:
      context: ./backend

    container_name: tareas_backend
    restart: unless-stopped

    environment:
      PORT: 4000
      DB_HOST: db
      DB_NAME: gestor-tareas
      DB_USER: postgres
      DB_PASS: 1234
      NODE_ENV: production

    depends_on:
      - db

    ports:
      - "4000:4000"

    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
    
    container_name: tareas_frontend
    restart: unless-stopped

    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: tareas_nginx
    depends_on:
      - frontend
      - backend
    
    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge